model:
  base_learning_rate: 0.0002
  target: models.flow.TriplaneFlow.TriFlow
  params:
    stage: 2
    pretrained_ldm_ckpt: "/path/to/project/ckpts/TriFlow.ckpt"
    unet_config:
      target: models.flow.cldm.ControlLDM
      params:
        hint_channel: 96
        control_key: hint
        in_channels: 48
        compress_channels: -1
        model_channels: 384
        out_channels: 48
        num_res_blocks: 2
        attention_resolutions: [4,8]
        dropout: 0.0
        channel_mult: [1, 2, 3, 4]
        conv_resample: True
        dims: 2
        num_classes: 7
        use_checkpoint: False
        num_heads: 4
        num_head_channels: 64
        num_heads_upsample: -1
        use_scale_shift_norm: True
        use_flash_attention: True
        resblock_updown: False
        use_new_attention_order: True
        with_fourier_features: False

    latent_shape: [48, 64, 64]  # [3, 4, 128, 128]
    ode_method: midpoint
    ode_opts:
      step_size: 0.02
    use_ema: True
    optm_betas: [0.9,0.999]

    mean: ~
    std: ~

    first_stage_config:
      target: models.triplane.TriplaneVQVAE.TriplaneVQVAE
      params:
        model_config:
          target: models.triplane.Triplane.TriplaneVQVAE
          params:
            in_ch: 1
            out_ch: 1
            base_ch: 32
            res: [256,256,256]
            ch_mult: [1,2,4]
            feat_ch: 64
            proj_conv: 2
            embed_dim: 16
            n_embed: 8192
            decay: 0.99
            restart_thres: 1.0
            mlp_ch: 384
            PE_ch: 32
            commitment_weight: 0.25
            norm_type: group
            affine: true
            swish: false
            num_groups: 8

        lambda_recon: 2.0
        hybrid_loss_config:
          target: models.triplane.loss.HybridLoss
          params:
            lpips_start_iter: 30000 # 55 epochs
            lambda_lpips: 0.1
            sample_ratio: 0.01
            downsample_ratio: 1.0
        gan_loss_config:
          target: models.triplane.loss.GANLoss
          params:
            disc_channels: 32
            disc_layers: 3
            disc_loss_type: hinge
            adaptive_g_weight: True
            lambda_g: 0.1
            lambda_gf: 2.0
            lambda_d: 1.0

        disc_start_iter: 60000 # 135 epochs
        lr_disc: 0.0005
        gan_patch_size: [128,128,128]
        scheduler_config: null
        chunk_size: 1048576
        resolution: 256

        save_gt: true
        save_zq: false
        save_latent: true
        mamual_backward: true
        finetune_from: ~
        accumulate_grad_batches: 2

    first_stage_ckpt: "/path/to/project/ckpts/TriplaneVQVAE.ckpt"
    vol_res: 256
    cls_names_id:
      CTChestAbdomen: 1
      CTHeadNeck: 2
      CTLegs: 3
      MRBody: 4
      MRBrain/T1: 5
      MRBrain/T2: 6

data:
  target: data.Triplane.Volume
  params:
    split_path: /path/to/project/data/split-All.npy
    num_pts:
    - 10000
    - 30000
    - 30000
    - 20000
    - 10000
    sigmas:
    - 1.0
    - 0.1
    - 0.01
    - 0.001
    - 0.0

    cls_names_id:
      CTChestAbdomen: 1
      CTHeadNeck: 2
      CTLegs: 3
      MRBody: 4
      MRBrain/T1: 5
      MRBrain/T2: 6

    latent_path: /path/to/project/data/latents/TriplaneDCAE-VQ-f64d8c64-All/test/
    cond_path: /path/to/project/exp/test_TriplaneVQVAE_infer/infer_SVR_latent/
    only_latent: true

    balanced: true
    random_aug: false
    fixed_aug: 0
    gen_latent: false
    task_path: ~
    path_include: ['CTChestAbdomen', 'CTHeadNeck', 'CTLegs']

    batch_size: 64
    val_batch_size: 4
    num_workers: 8
    val_num_workers: 2
    pin_memory: false
    distributed: true

lightning:
  modelcheckpoint:
    params:
      every_n_train_steps: 1000
  callbacks: {}
  trainer:
    benchmark: true
    val_check_interval: 5000
    num_sanity_val_steps: 0
    check_val_every_n_epoch: null
    max_epochs: -1
    max_steps: -1
    sync_batchnorm: true
    accumulate_grad_batches: 1
    gradient_clip_val: 1.0
    devices: [0,1,2,3]
    num_nodes: 1
    precision: bf16-mixed
