model:
  base_learning_rate: 0.0005
  target: models.triplane.TriplaneVQVAE.TriplaneVQVAE
  params:
    model_config:
      target: models.triplane.Triplane.TriplaneVQVAE
      params:
        in_ch: 1
        out_ch: 1
        base_ch: 32
        res:
        - 256
        - 256
        - 256
        ch_mult:
        - 1
        - 2
        - 4
        feat_ch: 64
        proj_conv: 2
        embed_dim: 16
        n_embed: 8192
        decay: 0.99
        restart_thres: 1.0
        mlp_ch: 384
        PE_ch: 32
        commitment_weight: 0.25
        norm_type: group
        affine: true
        swish: false
        num_groups: 8
    lambda_recon: 2.0
    hybrid_loss_config:
      target: models.triplane.loss.HybridLoss
      params:
        lpips_start_iter: 30000
        lambda_lpips: 0.1
        sample_ratio: 0.01
        downsample_ratio: 1.0
    gan_loss_config:
      target: models.triplane.loss.GANLoss
      params:
        disc_channels: 32
        disc_layers: 3
        disc_loss_type: hinge
        adaptive_g_weight: true
        lambda_g: 0.1
        lambda_gf: 2.0
        lambda_d: 1.0
    disc_start_iter: 60000
    lr_disc: 0.0005
    gan_patch_size:
    - 128
    - 128
    - 128
    scheduler_config: null
    chunk_size: 1048576
    resolution: 256
    save_gt: true
    save_zq: true
    save_latent: true
    mamual_backward: true
    finetune_from: null
    accumulate_grad_batches: 2
data:
  target: data.Triplane.Volume
  params:
    split_path: /path/to/project/data/split-All.npy
    num_pts:
    - 10000
    - 30000
    - 30000
    - 20000
    - 10000
    sigmas:
    - 1.0
    - 0.1
    - 0.01
    - 0.001
    - 0.0
    cls_names_id:
      CTChestAbdomen: 1
      CTHeadNeck: 2
      CTLegs: 3
      MRBody: 4
      MRBrain/T1: 5
      MRBrain/T2: 6
    latent_path: null
    cond_path: null
    only_latent: false
    balanced: true
    random_aug: true
    fixed_aug: 0
    gen_latent: false
    task_path: null
    path_include: null
    batch_size: 1
    val_batch_size: 1
    num_workers: 4
    val_num_workers: 4
    distributed: true
lightning:
  modelcheckpoint:
    params:
      every_n_train_steps: 500
  callbacks: {}
  trainer:
    benchmark: true
    val_check_interval: 5000
    num_sanity_val_steps: 0
    check_val_every_n_epoch: null
    max_epochs: -1
    sync_batchnorm: true
    devices:
    - 0
    - 1
    - 2
    - 3
    num_nodes: 1
    precision: bf16-mixed
